name: Pipeline de CI/CD pour RAIN

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      # --- ÉTAPE DE NETTOYAGE SIMPLIFIÉE ---
      - name: Free up disk space on runner
        run: |
          echo "Initial free space:"
          df -h
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          echo "Space after cleanup:"
          df -h
      # --- MODIFICATION CLÉ : On crée le fichier .env dynamiquement ---
      - name: Create .env file for Docker Compose
        run: |
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> Docker/.env
          echo "DB_USER=${{ secrets.DB_USER }}" >> Docker/.env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> Docker/.env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> Docker/.env
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> Docker/.env
          echo "MONGODB_NAME=${{ secrets.MONGODB_NAME }}" >> Docker/.env
          echo "MONGODB_USER=${{ secrets.MONGODB_USER }}" >> Docker/.env
          echo "MONGODB_PASSWORD=${{ secrets.MONGODB_PASSWORD }}" >> Docker/.env
          echo "MONGODB_HOST=${{ secrets.MONGODB_HOST }}" >> Docker/.env
          echo "MONGODB_PORT=${{ secrets.MONGODB_PORT }}" >> Docker/.env
          echo "BASE_URL=${{ secrets.BASE_URL }}" >> Docker/.env
          echo "MODEL_SAVE_PATH=${{ secrets.MODEL_SAVE_PATH }}" >> Docker/.env
          echo "EMBEDDINGS_SAVE_PATH=${{ secrets.EMBEDDINGS_SAVE_PATH }}" >> Docker/.env
          echo "MODEL_EMBEDDING_NAME=${{ secrets.MODEL_EMBEDDING_NAME }}" >> Docker/.env
          echo "MLFLOW_DB_NAME=${{ secrets.MLFLOW_DB_NAME }}" >> Docker/.env
          echo "MLFLOW_TRACKING_URL=${{ secrets.MLFLOW_TRACKING_URL }}" >> Docker/.env
          echo "GRA_DOCKER_PORT=${{ secrets.GRA_DOCKER_PORT }}" >> Docker/.env
          echo "MLFLOW_DOCKER_PORT=${{ secrets.MLFLOW_DOCKER_PORT }}" >> Docker/.env
          echo "PROM_DOCKER_PORT=${{ secrets.PROM_DOCKER_PORT }}" >> Docker/.env
          echo "DB_DOCKER_PORT=${{ secrets.DB_DOCKER_PORT }}" >> Docker/.env
          echo "MONGODB_DOCKER_PORT=${{ secrets.MONGODB_DOCKER_PORT }}" >> Docker/.env
          echo "STREAMLIT_DOCKER_PORT=${{ secrets.STREAMLIT_DOCKER_PORT }}" >> Docker/.env
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> Docker/.env

      - name: Verify files exist
        run: |
          echo "Listing files in Docker directory:"
          ls -la Docker/

      - name: Build and Run Docker Compose
        working-directory: ./Docker
        run: docker compose up -d --build

      - name: Wait for Services to be Healthy
        working-directory: ./Docker
        run: |
          echo "Waiting for services..."
          sleep 60 
          docker compose ps
          echo "Services are up!"

      - name: Run Tests
        working-directory: ./Docker
        run: docker compose exec -T api pytest Tests/

  push-to-registry:
    needs: build-and-test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GIT_TOKEN }}

      - name: Build and push API image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./API/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/rain-api:latest

      - name: Build and push UI image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./UI/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/rain-ui:latest

      - name: Build and push MLflow image
        uses: docker/build-push-action@v5
        with:
          context: ./Docker
          file: ./Docker/mlflow/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/rain-mlflow:latest